/**
 * The handful of ratios a beginner is asked to read, as arithmetic.
 *
 * Deliberately thin. None of this is clever — it is the four or five divisions
 * that every screener performs and then presents as a verdict. Having them here
 * rather than typed into lesson prose means an explainer can show WHY leverage
 * flatters return on equity by computing both numbers from the same balance
 * sheet, instead of asserting it and hoping.
 *
 * Every function takes a plain object and returns a number. No opinions, no
 * thresholds, no "good/bad" — where a threshold matters it belongs in the
 * content next to the sentence that justifies it, because thresholds are
 * judgements and these are facts.
 */

/** A stripped-down set of figures — enough for every ratio below. */
export interface Financials {
  /** Profit after tax, as reported. */
  netProfit: number;
  /** Cash actually generated by the business over the same period. */
  operatingCashFlow: number;
  /** Profit before interest and tax. */
  operatingProfit: number;
  /** Interest owed on borrowings over the period. */
  interestCost: number;
  /** Shareholders' funds. */
  equity: number;
  /** Interest-bearing borrowings. */
  debt: number;
  totalAssets: number;
  currentAssets: number;
  currentLiabilities: number;
}

function safeDivide(numerator: number, denominator: number): number {
  if (denominator === 0) return Number.NaN;
  return numerator / denominator;
}

/** Profit per rupee of shareholders' own money. Flattered by borrowing. */
export function returnOnEquity(f: Financials): number {
  return safeDivide(f.netProfit, f.equity) * 100;
}

/**
 * Profit per rupee of ALL money in the business, borrowed or not.
 *
 * The pair matters more than either number. A company can lift return on equity
 * simply by replacing equity with debt — the numerator barely moves and the
 * denominator shrinks — while this one stays exactly where it was. That gap is
 * the single most useful thing on a screener and almost nobody looks at it.
 */
export function returnOnCapitalEmployed(f: Financials): number {
  return safeDivide(f.operatingProfit, f.equity + f.debt) * 100;
}

/** Profit per rupee of assets, however they were funded. */
export function returnOnAssets(f: Financials): number {
  return safeDivide(f.netProfit, f.totalAssets) * 100;
}

export function debtToEquity(f: Financials): number {
  return safeDivide(f.debt, f.equity);
}

/**
 * How many times over the operating profit covers the interest bill.
 *
 * The ratio that decides whether debt is a tool or a countdown. Below about
 * 1.5x a single bad quarter stops being a disappointment and starts being a
 * solvency question — but the threshold is a judgement, so it lives in the
 * content, not here.
 */
export function interestCoverage(f: Financials): number {
  return safeDivide(f.operatingProfit, f.interestCost);
}

export function currentRatio(f: Financials): number {
  return safeDivide(f.currentAssets, f.currentLiabilities);
}

/**
 * How much of the reported profit never arrived as cash, as a percentage.
 *
 * Zero means every rupee of profit showed up in the bank. A large positive
 * number means profit was recognised on business that has not paid yet — which
 * is legal, ordinary, and the place trouble hides longest, because it can
 * continue for years before anything looks wrong.
 */
export function accrualGap(f: Financials): number {
  return safeDivide(f.netProfit - f.operatingCashFlow, Math.abs(f.netProfit)) * 100;
}

/** Cash generated per rupee of reported profit. 1.0 is a clean year. */
export function cashConversion(f: Financials): number {
  return safeDivide(f.operatingCashFlow, f.netProfit);
}
