/**
 * Edge or Luck — telling a real edge from a run of good fortune.
 *
 * WHY THIS GAME EXISTS
 *
 * SEBI's studies of the equity F&O segment found that more than **75% of
 * loss-making traders kept trading after consecutive losing years**. That is the
 * central failure of Indian retail trading, and it is not ignorance of
 * candlesticks. It is that a losing year reads as bad luck rather than as
 * evidence, because almost nobody can tell the difference — in either direction.
 *
 * So this module answers one question, twice: **could this record have happened
 * by chance?** First about invented traders, where the answer is checkable
 * because we know how each record was generated. Then about the learner's own
 * filed runs, where it usually stings.
 *
 * THE MEASURE IS EXPECTANCY, NOT WIN RATE
 *
 * Judging a record on win rate would teach something false. A trader who wins
 * 40% of the time with three-to-one winners has a genuine edge; one who wins 70%
 * of the time scalping for a quarter of what they risk does not. Both exist in
 * the deck below, on purpose, because "high win rate = good trader" is the
 * misconception this game is most useful for breaking.
 *
 * Everything here therefore works in **R-multiples** — profit as a multiple of
 * the money risked on that trade. A trade risking ₹2,000 that made ₹6,000 is
 * +3R whether the account is ₹50,000 or ₹5 crore, which is what makes records
 * comparable at all.
 */

import { mulberry32 } from '@/lib/util/rng';

/** How many resamples the null distribution is built from. */
const BOOTSTRAP_SAMPLES = 2000;

/**
 * One-sided 95%. A trader asking "do I have an edge" is asking about one tail;
 * nobody runs this hoping to prove they are reliably bad.
 */
const Z_95_ONE_SIDED = 1.645;

/**
 * No record is ever called proven below this many trades, whatever the p-value.
 *
 * A bootstrap on six trades will happily report significance — six wins in a row
 * is genuinely unlikely under a fair coin — and it would be the single most
 * damaging thing this game could say. The whole point is that short records
 * cannot be read, so a learner with a handful of lucky runs must not be handed
 * a certificate. The statistic is not wrong; it is being asked a question it has
 * no business answering, and this is where that gets refused.
 */
export const MIN_TRADES_FOR_A_VERDICT = 30;

/**
 * What the learner is asked to conclude.
 *
 * Three answers rather than two, and the third is the point of the game.
 *
 * "Edge or luck?" is the wrong question, because for most real track records
 * the honest answer is neither — there is simply not enough of it to say. Ask it
 * as a binary and a learner is forced to guess, learns that guessing sometimes
 * works, and takes away the exact habit that makes people trade a system for
 * twelve trades and then draw a conclusion from it.
 *
 * `unproven` is the most common correct answer in the deck below. That
 * distribution is deliberate and is most of the teaching.
 */
export type Answer =
  /** The record is strong enough, and long enough, to be convincing. */
  | 'edge'
  /** The expectancy is negative. Not unlucky — arithmetically losing. */
  | 'no-edge'
  /** Could easily be chance. Not a verdict, an admission the sample is too small. */
  | 'unproven';

export const ANSWER_LABELS: Record<Answer, string> = {
  edge: 'Yes — there is a real edge here',
  'no-edge': 'No — this loses money by design',
  unproven: 'Not enough trades to say either way',
};

export type Truth =
  /** Generated by coin flips. There is no edge, whatever the curve looks like. */
  | 'coin'
  /** A real, positive expectancy. */
  | 'edge'
  /** Coin flips with costs subtracted — the F&O default, and a certain loser. */
  | 'drag';

export interface TrackRecord {
  id: string;
  /** How the trader describes themselves. Deliberately confident. */
  claim: string;
  /** Anything a learner can legitimately reason from before deciding. */
  context: string;
  /** R-multiples, one per trade, in the order they happened. */
  trades: number[];
  /**
   * The defensible conclusion from the record ALONE — what a careful analyst
   * should answer. Stated explicitly per record rather than derived by a rule,
   * because two of these turn on arithmetic (a payoff that cannot add up) and
   * the rest on sample size, and one rule covering both would be a fragile
   * thing to hang the scoring on. A test checks each against the statistics.
   */
  correct: Answer;
  /**
   * How the record was really generated — which is NOT always the same as
   * `correct`, and the gap is where the game does its work. A coin can produce
   * a record nobody could call, and a real edge can hide inside one.
   */
  truth: Truth;
  /** Said only after the learner has committed. */
  explanation: string;
}

export interface Assessment {
  n: number;
  wins: number;
  winRate: number;
  /** Average R per trade. This is the edge, if there is one. */
  meanR: number;
  sdR: number;
  totalR: number;
  /** Largest peak-to-trough fall in cumulative R. */
  maxDrawdownR: number;
  /**
   * How often pure chance produces a record at least this good, given the same
   * trade sizes. 0.5 means a coin does this half the time.
   */
  pValue: number;
  /** Below 0.05 one-sided. Deliberately NOT called "proof" anywhere in the UI. */
  significant: boolean;
  /**
   * Trades needed before a record of this quality would clear the bar. Null
   * when the mean is not positive, because no amount of a losing record ever
   * becomes evidence of an edge.
   */
  tradesNeeded: number | null;
  /** Cumulative R after each trade, for drawing the curve. */
  curve: number[];
}

export function cumulative(trades: number[]): number[] {
  let total = 0;
  return trades.map((r) => (total += r));
}

function mean(xs: number[]): number {
  return xs.length === 0 ? 0 : xs.reduce((a, b) => a + b, 0) / xs.length;
}

/** Sample standard deviation — n-1, because a track record is a sample. */
function stdDev(xs: number[]): number {
  if (xs.length < 2) return 0;
  const m = mean(xs);
  return Math.sqrt(xs.reduce((a, x) => a + (x - m) ** 2, 0) / (xs.length - 1));
}

/**
 * A bootstrap test of "the true edge is zero", rather than a t-test.
 *
 * Two reasons. R-multiples are badly skewed — a handful of +4R winners against
 * a wall of -1R losers is the normal shape of a trend-following record, and the
 * t-test's symmetry assumption is worst exactly there. And the bootstrap can be
 * explained to a beginner in one sentence, which a t-statistic cannot: *we
 * shuffled your own trades two thousand times with the edge taken out, and
 * counted how often chance alone beat what you actually did.*
 *
 * Seeded, so the same record always returns the same number. A learner who
 * reruns a scenario and sees a different p-value concludes the site is guessing.
 */
export function nullProbability(trades: number[], seed: number, samples = BOOTSTRAP_SAMPLES): number {
  if (trades.length === 0) return 1;
  const observed = mean(trades);
  // Centred, so the resampled world is the same trades with no edge in them.
  const centred = trades.map((r) => r - observed);

  const rand = mulberry32(seed);
  let atLeastAsGood = 0;
  for (let s = 0; s < samples; s++) {
    let total = 0;
    for (let i = 0; i < trades.length; i++) total += centred[Math.floor(rand() * trades.length)];
    if (total / trades.length >= observed) atLeastAsGood++;
  }

  // +1 top and bottom so a p-value is never exactly zero. No finite number of
  // resamples can establish that something is impossible, and printing "0.000"
  // would claim precisely that.
  return (atLeastAsGood + 1) / (samples + 1);
}

/**
 * How many trades before a record this good would be convincing.
 *
 * Rearranged from the one-sided z-test: the record clears the bar once
 * `mean / (sd / sqrt(n)) >= z`, so `n >= (z * sd / mean)^2`. It assumes the
 * trader keeps performing exactly as they have, which is generous — and the
 * number is still usually large enough to be the whole lesson.
 */
export function tradesNeededForSignificance(meanR: number, sdR: number): number | null {
  if (meanR <= 0) return null;
  if (sdR === 0) return 1;
  return Math.ceil((Z_95_ONE_SIDED * sdR / meanR) ** 2);
}

export function maxDrawdown(curve: number[]): number {
  let peak = 0;
  let worst = 0;
  for (const point of curve) {
    if (point > peak) peak = point;
    if (peak - point > worst) worst = peak - point;
  }
  return worst;
}

export function assess(trades: number[], seed = 1): Assessment {
  const n = trades.length;
  const wins = trades.filter((r) => r > 0).length;
  const meanR = mean(trades);
  const sdR = stdDev(trades);
  const curve = cumulative(trades);
  const pValue = nullProbability(trades, seed);

  return {
    n,
    wins,
    winRate: n === 0 ? 0 : wins / n,
    meanR,
    sdR,
    totalR: curve.length === 0 ? 0 : curve[curve.length - 1],
    maxDrawdownR: maxDrawdown(curve),
    pValue,
    significant: pValue < 0.05 && n >= MIN_TRADES_FOR_A_VERDICT,
    tradesNeeded: tradesNeededForSignificance(meanR, sdR),
    curve,
  };
}

// ---------------------------------------------------------------------------
// Generating records
// ---------------------------------------------------------------------------

/**
 * Coin flips. Win or lose the same amount, half the time each — no edge at all,
 * by construction, however convincing the curve turns out to look.
 */
export function coinFlips(n: number, seed: number): number[] {
  const rand = mulberry32(seed);
  return Array.from({ length: n }, () => (rand() < 0.5 ? 1 : -1));
}

/** A real edge: `winRate` of the time you make `reward` R, otherwise you lose 1R. */
export function withEdge(n: number, winRate: number, reward: number, seed: number): number[] {
  const rand = mulberry32(seed);
  return Array.from({ length: n }, () => (rand() < winRate ? reward : -1));
}

/**
 * Coin flips minus costs on every trade.
 *
 * This is the shape of the ₹1.05 lakh crore SEBI reported Indian individuals
 * losing in F&O in FY25, and it is worth being able to recognise: the decisions
 * are a coin, the curve drifts down anyway, and no amount of getting better at
 * calling direction fixes it. `cost` is expressed in R because that is what the
 * rest of this module speaks — 0.08 is a trade risking ₹2,000 that pays ₹160
 * in brokerage, STT, stamp duty, exchange and GST to open and close.
 */
export function coinFlipsWithCosts(n: number, cost: number, seed: number): number[] {
  return coinFlips(n, seed).map((r) => r - cost);
}

/**
 * The deck.
 *
 * Ordered so the first record is an easy "luck" and the second is the one that
 * breaks the win-rate misconception, because a learner who gets the second one
 * wrong pays attention to every record after it.
 *
 * Every claim is written the way this actually sounds in India — a Telegram
 * channel, a Bank Nifty weekly expiry, a cousin with a tip — because a learner
 * recognising the voice is half of recognising the pattern.
 */
export const TRACK_RECORDS: TrackRecord[] = [
  {
    id: 'hot-hand',
    claim: '"I have cracked Bank Nifty weekly expiry. 8 wins out of 12. Starting a paid group next month."',
    context: '12 trades over three weeks, up 4R. Every trade risked the same amount and paid the same when it won.',
    trades: coinFlips(12, 14),
    correct: 'unproven',
    truth: 'coin',
    explanation:
      'These twelve trades are literal coin flips. The computer drew them 50/50 with equal win and loss sizes, and this is what came out: eight winners, up 4R, and a curve anyone would put in a screenshot. A run at least this good happens by chance about one time in five, so twelve trades can tell you nothing whatsoever — the honest answer was that there is not enough here. The paid group is the tell. The reliable money in that plan comes from subscriptions, not from trading.',
  },
  {
    id: 'low-win-rate',
    claim: '"I lose more often than I win — 14 winners out of 40. I am probably not cut out for this."',
    context: '40 trades over eight months, up 21.6R. Losses cut at 1R; winners held much longer.',
    trades: withEdge(40, 0.35, 3.4, 32),
    correct: 'unproven',
    truth: 'edge',
    explanation:
      'This is the best trader in the deck, and they are about to quit. A 35% win rate sounds like failure until you see the winners are worth about three and a half times the losers — the expectancy is strongly positive and this record was generated with a genuine edge in it. And still: 40 trades is not enough to PROVE it. Chance produces a stretch this good around 8% of the time, which does not clear the usual bar. That asymmetry is the cruellest thing about trading. A real edge takes hundreds of trades to demonstrate, while the feeling of failing arrives after ten — so the people best equipped to succeed are the ones most likely to stop.',
  },
  {
    id: 'the-grinder',
    claim: '"70% strike rate. I take small, safe profits and never let a winner turn into a loser."',
    context: '50 trades of intraday scalping, 35 of them winners. Down 2.75R. Targets are quick; a loss is a full stop.',
    trades: withEdge(50, 0.7, 0.35, 18),
    correct: 'no-edge',
    truth: 'coin',
    explanation:
      'You did not need statistics for this one, only arithmetic. Each win pays about 0.35R and each loss costs a full 1R, so seven wins in ten earns 2.45R and three losses give back 3.0R. It loses money by construction, before a rupee of brokerage. "Never let a winner turn into a loser" is the disposition effect with a motivational caption on it — cutting winners early and holding losers to a full stop is precisely the wrong way round. The strike rate is real. It is simply not worth anything.',
  },
  {
    id: 'the-drag',
    claim: '"My calls are right about half the time. I just need to improve my accuracy slightly."',
    context: '60 trades of index options over four months, 30 winners, down 4.8R. Same size each time, held minutes.',
    trades: coinFlipsWithCosts(60, 0.08, 5),
    correct: 'no-edge',
    truth: 'drag',
    explanation:
      'The direction calls really are a coin — exactly 30 right out of 60 — and the account shrinks anyway, because every round trip pays brokerage, STT, stamp duty, exchange turnover, SEBI fees and GST. At this size that is about 8% of the amount risked, on every single trade. Sixty trades hands roughly 5R to the system. "Improve accuracy slightly" does not fix it: break-even here is not 50% but about 54%, and it moves further away the more often you trade. This is the shape of the ₹1.05 lakh crore Indian individuals lost in F&O in FY25.',
  },
  {
    id: 'the-drawdown',
    claim: '"I was down more than 13R at one point. The strategy stopped working, so I have switched to a new one."',
    context: '55 trades over a year on one system throughout, 27 winners, finishing up 23.3R.',
    trades: withEdge(55, 0.45, 1.9, 64),
    correct: 'edge',
    truth: 'edge',
    explanation:
      'A real edge, and the only record here long enough and strong enough to prove it — chance produces this about once in eighty times. It is also the one being abandoned. A system with these numbers spends much of its life underwater, and a 13R hole is an ordinary event for it rather than evidence that anything broke. This trader has mistaken a bad stretch for a dead strategy and is about to restart the clock at zero on something they know far less about. Knowing what a normal drawdown looks like for your own system is exactly what lets you sit through one.',
  },
  {
    id: 'the-tip-account',
    claim: '"Been following a Telegram channel for two months. Up 6R. The admin posts winning screenshots daily."',
    context: '18 trades, every one taken from the same channel. 12 winners.',
    trades: coinFlips(18, 14),
    correct: 'unproven',
    truth: 'coin',
    explanation:
      'Coin flips again, and a flattering run of them — twelve winners from eighteen, up 6R, from a generator with no skill in it at all. Eighteen trades cannot separate a tipster from a coin, which is exactly why the channel shows you two months rather than two years, and why you see winners as screenshots rather than the whole record. Anyone posting hundreds of calls can assemble a highlight reel afterwards. SEBI has been unwinding precisely this: about 62% of Indian retail investors follow finfluencers, and roughly 2% of those are registered to advise anybody.',
  },
];

/**
 * The learner's own record, judged by the same test.
 *
 * Takes the P&L of each filed run rather than R-multiples, because that is what
 * the games actually store. Converting is the honest part: without a recorded
 * risk per trade there is no true R, so the runs are normalised by their own
 * average absolute size. That measures consistency of outcome rather than a
 * genuine edge, which is a weaker claim — and the UI says so rather than
 * quietly presenting it as the same thing.
 */
export function assessOwnRuns(pnls: number[], seed = 7): Assessment | null {
  if (pnls.length < 5) return null;
  const scale = mean(pnls.map(Math.abs));
  if (scale === 0) return null;
  return assess(pnls.map((p) => p / scale), seed);
}
